
[Uncategorized]
	# 
	#Range: > -2147483648
	configVersion = 2

["Ender Dragon"]
	#What is the initial state of the Ender Dragon in the End?
	#If 'default', she will be present and attack players, just like the vanilla game.
	#If 'passive_dragon', she will be present, but idly noodle about until a player provokes her first.
	#If 'calm', the End will not contain an Ender Dragon by default.
	#Note: If you choose 'calm', you should also change the 'portalInitialState' setting, so it is possible to leave the End.
	#Default: default
	dragonInitialState = "passive_dragon"
	#What is the initial state of the End Portal in the center of the main End Island?
	#If 'closed', it will not be usable until the first Ender Dragon dies, just like in vanilla.
	#If 'open', it will already be open.
	#If 'open_with_egg', it will already be open and a Dragon Egg will be present.
	#Default: closed
	portalInitialState = "open"
	#How many End Gateways will be available when first entering the End, without any Dragons having to die?
	#Default: 0
	#Range: > -2147483648
	initialEndGatewayCount = 4
	#What happens when a player places four End Crystals onto the exit End Portal?
	#If 'default', a new Ender Dragon will be summoned and she will attack the player, just like in vanilla.
	#If 'spawn_gateway', the mechanic will be replaced with one that directly creates an End Gateway, with no fighting required.
	#If 'disabled', nothing will happen.
	#Default: default
	resummonSequence = "default"
	#If 'true', and 'dragonInitialState' is 'calm', players automatically earn the Free the End advancement when visiting the End.
	#If 'true', and 'resummonSequence' is 'spawn_gateway', players earn the advancement for resummoning the Dragon when using the spawn_gateway mechanic.
	#Has no effects otherwise. Probably should be left as 'true'.
	#Default: true
	simulacraDragonAdvancements = false
	#Can the Dragon perform the 'strafe_player' or 'charging_player' actions?
	#strafe_player is the one where she shoots a fireball.
	#charge_player is the one where she tries to fly into you.
	#If 'false', she will perform the 'landing_approach' action instead, which will cause her to perch on the portal.
	#Default: true
	dragonFlies = true
	#Can the Dragon perform the 'sitting_flaming' or 'sitting_attacking' actions?
	#sitting_flaming is the one where she perches on the End portal and pours out a puddle of dragon's breath.
	#sitting_attacking is when she roars at you.
	#If 'false', she will perform the 'sitting_scanning' action instead, which will soon lead to her leaving her perch.
	#Default: true
	dragonSits = true
	#Does the Dragon deal contact damage?
	#Default: true
	dragonDamage = true
	#Does the Dragon knock back nearby entities, and damage them while she's sitting?
	#Default: true
	dragonKnockback = true

[Wither]
	#Comma-separated list of difficulties where the Wither is enabled.
	#If the current world difficulty does not appear in the set, building the Wither formation will spawn a Nether Star
	#item, and give you the advancement for killing the Wither.
	#Default: easy, normal, hard
	witherDifficulties = "normal, hard"
	#Is the Wither allowed to intentionally target players?
	#Default: true
	witherTargetsPlayers = false
	#Is the Wither allowed to intentionally target non-players?
	#Default: true
	witherTargetsMobs = true
	#Can the Wither fire black wither skulls?
	#Default: true
	blackWitherSkulls = true
	#Can the Wither fire blue ('charged') wither skulls on Normal and Hard difficulty?
	#Default: true
	blueWitherSkulls = true
	#Does the Wither break nearby blocks after it gets damaged?
	#Default: true
	witherBreaksBlocks = true

["Elder Guardian"]
	#This option affects your own client.
	#What happens when an Elder Guardian gives you the Mining Fatigue effect?
	#If 'default', the sound effect and particle appear.
	#If 'only_sound', only the sound plays, and if 'only_particle', only the particle effect appears.
	#If 'disabled', neither of those happen.
	#Default: default
	elderGuardianEffect = "only_sound"

