
[Uncategorized]
	# 
	#Range: > -2147483648
	configVersion = 0

[Optimization]
	#By default, mobs that are currently attacking a player do not check every tick if it's still okay to do so.
	#This is how often the mob will check. (Set this to 1 to check every tick.)
	#Note that the checks are staggered, and changes to this setting can take a couple moments to come into effect.
	#Default: 20
	#Range: > -2147483648
	recheckInterval = 20
	#Should Apathy attempt to optimize the rule in the config file, to do less work per tick?
	#If your rule is doing something unexpected, or isn't working like it should, try turning this off.
	#And report it too, since it's definitely a bug, lol.
	#Default: true
	runRuleOptimizer = true

["Wow even more misc options"]
	#Comma-separated list of difficulties where zombies are allowed to attack villagers.
	#Default: easy, normal, hard
	zombieAttackVillagerDifficulties = "easy, normal, hard"

["Revenge Spread"]
	#Comma-separated list of difficulties.
	#If the current world difficulty appears in the set, zombified piglins will alert their friends
	#when a player provokes one. This will also spread Apathy's revengeTimer to them.
	#Default: easy, normal, hard
	angryPiggies = "normal, hard"
	#Let's say this option is set to 10, and you attack a zombie. Other zombies within 10 blocks will have their revengeTimer set, too.
	#This option affects mobs of the same type only.
	#Please recall that the revengeTimer is an Apathy concept, and Apathy only ever suppresses normal mob AI.
	#i.e, this won't cause a mob to attack a player that already wasn't going to.
	#Default: 0
	#Range: > -2147483648
	sameTypeRevengeSpread = 0
	#When attacking any mob, other mobs within this range will have their revengeTimer set, too.
	#This option affects all mobs, whether they have the same type or not.
	#Please recall that the revengeTimer is an Apathy concept, and Apathy only ever suppresses normal mob AI.
	#i.e, this won't cause a mob to attack a player that already wasn't going to.
	#Default: 0
	#Range: > -2147483648
	differentTypeRevengeSpread = 0

[Debug]
	#If 'true', Apathy will dump the rule specified in the config file to the file 'apathy-dumps/builtin-rule.json'.
	#It will also dump the automatically optimized rule out to 'apathy-dumps/builtin-rule-opt.json'.
	#Maybe this is handy if you'd like to see what the .json format looks like for a particular config file.
	#Default: false
	debugBuiltinRule = false
	#If 'true', Apathy will dump the rule specified in mobs.json to the file 'apathy-dumps/json-rule.json'.
	#It will also dump the automatically optimized rule out to 'apathy-dumps/json-rule-opt.json'.
	#Default: false
	debugJsonRule = false

