#How many marks you can draw with a single chalk. Default: 64
#Range: > 0
ChalkUses = 200
#How many light glowing mark produces. Default: 5
#Range: 0 ~ 15
GlowingMarkLightLevel = 5
#If enabled, Chalks (and Chalk Boxes) will generate in Dungeons, Abandoned Mineshafts, Planes and Savanna villages, Cartographer houses
#Default: true
ShouldGenerateInChests = false
#Controls whether glowing should be enabled in Chalk Box.
#If disabled - you will not be able to draw glowing marks with chalk box.
#Default: true
ChalkBoxGlowingEnabled = true
#How many glowing marks one glowing item will give.
#Default: 8
#Range: 1 ~ 9999
ChalkBoxGlowingItemUses = 8

