#Scale the mini-map to a given pixel size.
forceMiniMapScaling = 92
#Scale the world-map to a given pixel size.
forceWorldMapScaling = 256
#If 'true', the Mini-Map of the Active Map will be drawn on the HUD while the Atlas is on your hot-bar or off-hand.
drawMiniMapHUD = true
#Controls location where mini-map displays. Any of: 'HANDS', 'HOTBAR', or 'INVENTORY'.
#Allowed Values: HANDS, HOTBAR, INVENTORY
activationLocation = "INVENTORY"
#Set to any of 'Upper'/'Lower' & 'Left'/'Right' to control anchor position of mini-map
#Allowed Values: UPPERRIGHT, UPPERLEFT, LOWERRIGHT, LOWERLEFT
minimapAchoring = "UPPERRIGHT"
#Enter an integer which will offset the mini-map horizontally
minimapHorizontalOffset = -4
#Enter an integer which will offset the mini-map vertically
minimapVerticalOffset = 4

